dbt_transformation:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_ID', '') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USERNAME', '') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"

      role: "{{ env_var('SNOWFLAKE_USER_ROLE', '') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', '') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', '') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', '') }}"
      threads: 1
      client_session_keep_alive: False
      query_tag: tag

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
  target: dev